from pathlib import Path

ROOT_DIR = Path(__file__).resolve().parent
DATA_DIR = ROOT_DIR / "data"
LOG_DIR = ROOT_DIR / "logs"
DB_PATH = DATA_DIR / "chainwatch.db"

TRANSACTION_TIMEOUT_SECONDS = 600
HIGH_AMOUNT_THRESHOLD = 1500.0

DEFAULT_SEVERITY = "MEDIUM"
SEVERITY_BY_TYPE = {
    "FAILED_TRANSACTION": "HIGH",
    "PENDING_TRANSACTION": "MEDIUM",
    "DUPLICATE_TRANSACTION_ID": "HIGH",
    "UNUSUALLY_HIGH_AMOUNT": "HIGH",
    "INVALID_AMOUNT": "CRITICAL",
    "APPLICATION_ERROR": "CRITICAL",
}
